import os
import sqlite3
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from flask import Flask, jsonify, redirect, render_template, request, session, url_for
from werkzeug.security import check_password_hash, generate_password_hash

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:  # pragma: no cover - installed in deployment environments
    psycopg = None
    dict_row = None

app = Flask(__name__)
app.config["SECRET_KEY"] = os.getenv("SECRET_KEY", "dev-only-change-me")
app.config["DEBUG"] = os.getenv("DEBUG", "False").lower() == "true"
app.config["DATABASE_PATH"] = os.getenv("DATABASE_PATH", str(Path(__file__).with_name("instance") / "quotes.db"))
app.config["DATABASE_URL"] = os.getenv("DATABASE_URL")


def database_query(query: str, parameters: tuple = ()) -> tuple[str, tuple]:
    if app.config["DATABASE_URL"]:
        return query.replace("?", "%s"), parameters
    return query, parameters


@dataclass
class QuoteRequest:
    id: int
    business_id: int | None
    customer_name: str
    email: str
    phone: str
    property_type: str
    bedrooms: int
    bathrooms: int
    frequency: str
    notes: str
    status: str = "new"
    estimated_price: int | None = None
    proposal: str = ""
    created_at: str = ""


@dataclass
class Business:
    id: int
    name: str
    email: str
    password_hash: str


def get_connection():
    if app.config["DATABASE_URL"]:
        if psycopg is None:
            raise RuntimeError("psycopg is required when DATABASE_URL is configured")
        return psycopg.connect(app.config["DATABASE_URL"], row_factory=dict_row)
    database_path = Path(app.config["DATABASE_PATH"])
    database_path.parent.mkdir(parents=True, exist_ok=True)
    connection = sqlite3.connect(database_path)
    connection.row_factory = sqlite3.Row
    return connection


def init_db() -> None:
    with get_connection() as connection:
        if app.config["DATABASE_URL"]:
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS businesses (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name TEXT NOT NULL,
                    email TEXT NOT NULL UNIQUE,
                    password_hash TEXT NOT NULL
                )
                """
            )
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS quote_requests (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    business_id INTEGER REFERENCES businesses(id),
                    customer_name TEXT NOT NULL,
                    email TEXT NOT NULL,
                    phone TEXT NOT NULL,
                    property_type TEXT NOT NULL,
                    bedrooms INTEGER NOT NULL,
                    bathrooms INTEGER NOT NULL,
                    frequency TEXT NOT NULL,
                    notes TEXT NOT NULL,
                    status TEXT NOT NULL,
                    estimated_price INTEGER,
                    proposal TEXT NOT NULL,
                    created_at TEXT NOT NULL
                )
                """
            )
            return
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS quote_requests (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                business_id INTEGER,
                customer_name TEXT NOT NULL,
                email TEXT NOT NULL,
                phone TEXT NOT NULL,
                property_type TEXT NOT NULL,
                bedrooms INTEGER NOT NULL,
                bathrooms INTEGER NOT NULL,
                frequency TEXT NOT NULL,
                notes TEXT NOT NULL,
                status TEXT NOT NULL,
                estimated_price INTEGER,
                proposal TEXT NOT NULL,
                created_at TEXT NOT NULL
            )
            """
        )
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS businesses (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                email TEXT NOT NULL UNIQUE,
                password_hash TEXT NOT NULL
            )
            """
        )
        columns = {row["name"] for row in connection.execute("PRAGMA table_info(quote_requests)")}
        if "business_id" not in columns:
            connection.execute("ALTER TABLE quote_requests ADD COLUMN business_id INTEGER")


def get_default_business_id() -> int:
    with get_connection() as connection:
        row = connection.execute(*database_query("SELECT id FROM businesses ORDER BY id LIMIT 1")).fetchone()
        if row:
            business_id = row["id"]
        else:
            cursor = connection.execute(
                *database_query("INSERT INTO businesses (name, email, password_hash) VALUES (?, ?, ?) RETURNING id", ("Clean Co.", "demo@clean.co", generate_password_hash("demo-password")))
            )
            business_id = cursor.fetchone()["id"]
        connection.execute(*database_query("UPDATE quote_requests SET business_id = ? WHERE business_id IS NULL", (business_id,)))
        return business_id


def get_business_by_email(email: str) -> Business | None:
    with get_connection() as connection:
        row = connection.execute(*database_query("SELECT * FROM businesses WHERE email = ?", (email,))).fetchone()
    return Business(**dict(row)) if row else None


def get_business(business_id: int) -> Business | None:
    with get_connection() as connection:
        row = connection.execute(*database_query("SELECT * FROM businesses WHERE id = ?", (business_id,))).fetchone()
    return Business(**dict(row)) if row else None


def row_to_request(row) -> QuoteRequest:
    return QuoteRequest(**dict(row))


def get_quote_request(request_id: int) -> QuoteRequest | None:
    with get_connection() as connection:
        row = connection.execute(*database_query("SELECT * FROM quote_requests WHERE id = ?", (request_id,))).fetchone()
    return row_to_request(row) if row else None


def get_quote_requests() -> list[QuoteRequest]:
    with get_connection() as connection:
        rows = connection.execute(*database_query("SELECT * FROM quote_requests ORDER BY id DESC")).fetchall()
    return [row_to_request(row) for row in rows]


def get_business_quote_requests(business_id: int) -> list[QuoteRequest]:
    with get_connection() as connection:
        rows = connection.execute(*database_query("SELECT * FROM quote_requests WHERE business_id = ? ORDER BY id DESC", (business_id,))).fetchall()
    return [row_to_request(row) for row in rows]


init_db()


def estimate_price(property_type: str, bedrooms: int, bathrooms: int, frequency: str) -> int:
    base_prices = {"home": 110, "apartment": 85, "office": 160, "airbnb": 95}
    frequency_adjustments = {"one-off": 1.0, "weekly": 0.82, "biweekly": 0.9, "monthly": 0.96}
    base = base_prices.get(property_type, 100)
    size_adjustment = max(0, bedrooms - 2) * 15 + max(0, bathrooms - 1) * 20
    return round((base + size_adjustment) * frequency_adjustments.get(frequency, 1.0))


@app.get("/")
def home():
    return render_template("home.html", business_id=get_default_business_id())


@app.get("/b/<int:business_id>")
def business_home(business_id: int):
    business = get_business(business_id)
    if business is None:
        return "Business not found", 404
    return render_template("home.html", business_id=business.id, business=business)


@app.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "GET":
        return render_template("auth.html", mode="register")
    name = request.form.get("name", "").strip()
    email = request.form.get("email", "").strip().lower()
    password = request.form.get("password", "")
    if not name or not email or len(password) < 8:
        return render_template("auth.html", mode="register", error="Name, email, and an 8-character password are required."), 400
    if get_business_by_email(email):
        return render_template("auth.html", mode="register", error="An account with that email already exists."), 400
    with get_connection() as connection:
        cursor = connection.execute(*database_query(
            "INSERT INTO businesses (name, email, password_hash) VALUES (?, ?, ?) RETURNING id",
            (name, email, generate_password_hash(password)),
        ))
        business_id = cursor.fetchone()["id"]
    session["business_id"] = business_id
    return redirect(url_for("dashboard"))


@app.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "GET":
        return render_template("auth.html", mode="login")
    email = request.form.get("email", "").strip().lower()
    business = get_business_by_email(email)
    if not business or not check_password_hash(business.password_hash, request.form.get("password", "")):
        return render_template("auth.html", mode="login", error="Email or password is incorrect."), 401
    session["business_id"] = business.id
    return redirect(url_for("dashboard"))


@app.post("/logout")
def logout():
    session.clear()
    return redirect(url_for("home"))


@app.post("/quote-requests")
def create_quote_request():
    form = request.form
    quote_request = QuoteRequest(
        id=0,
        business_id=int(form.get("business_id", get_default_business_id())),
        customer_name=form.get("customer_name", "").strip(),
        email=form.get("email", "").strip().lower(),
        phone=form.get("phone", "").strip(),
        property_type=form.get("property_type", "home"),
        bedrooms=int(form.get("bedrooms", 1)),
        bathrooms=int(form.get("bathrooms", 1)),
        frequency=form.get("frequency", "one-off"),
        notes=form.get("notes", "").strip(),
        created_at=datetime.now().strftime("%b %d, %Y at %H:%M"),
    )
    quote_request.estimated_price = estimate_price(
        quote_request.property_type,
        quote_request.bedrooms,
        quote_request.bathrooms,
        quote_request.frequency,
    )
    with get_connection() as connection:
        cursor = connection.execute(*database_query(
            """
            INSERT INTO quote_requests (
                business_id, customer_name, email, phone, property_type, bedrooms, bathrooms,
                frequency, notes, status, estimated_price, proposal, created_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id
            """,
            (
                quote_request.business_id,
                quote_request.customer_name,
                quote_request.email,
                quote_request.phone,
                quote_request.property_type,
                quote_request.bedrooms,
                quote_request.bathrooms,
                quote_request.frequency,
                quote_request.notes,
                quote_request.status,
                quote_request.estimated_price,
                quote_request.proposal,
                quote_request.created_at,
            ),
        ))
        quote_request.id = cursor.fetchone()["id"]
    return redirect(url_for("request_received", request_id=quote_request.id))


@app.get("/request-received/<int:request_id>")
def request_received(request_id: int):
    quote_request = get_quote_request(request_id)
    if quote_request is None:
        return "Quote request not found", 404
    return render_template("received.html", quote_request=quote_request)


@app.get("/dashboard")
def dashboard():
    business_id = session.get("business_id")
    if not business_id:
        return redirect(url_for("login"))
    business = get_business(business_id)
    return render_template("dashboard.html", requests=get_business_quote_requests(business_id), business=business)


@app.post("/api/quote-requests/<int:request_id>/proposal")
def generate_proposal(request_id: int):
    quote_request = get_quote_request(request_id)
    if quote_request is None or quote_request.business_id != session.get("business_id"):
        return jsonify({"error": "Quote request not found"}), 404
    quote_request.proposal = (
        f"Hi {quote_request.customer_name},\n\n"
        f"Thanks for requesting a cleaning quote. Based on your {quote_request.property_type} "
        f"and {quote_request.frequency} service, we can help for an estimated ${quote_request.estimated_price}. "
        "This includes a careful clean of the agreed rooms and a quality check before we leave.\n\n"
        "Reply to confirm a convenient time, and we will send the final booking details.\n\n"
        "Best,\nThe Clean Co."
    )
    with get_connection() as connection:
        connection.execute(*database_query(
            "UPDATE quote_requests SET proposal = ?, status = ? WHERE id = ?",
            (quote_request.proposal, "quoted", request_id),
        ))
    quote_request.status = "quoted"
    return jsonify({"proposal": quote_request.proposal, "status": quote_request.status})


@app.get("/api/health")
def health():
    return jsonify({"status": "ok", "service": "Cleaning Quote Platform"})


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=app.config["DEBUG"])